const hieroData = [
    { "glyph": "𓉐", "transliteration": "pr", "object": "집", "phonetic": "per", "sound_desc": "페르" },
    { "glyph": "𓎟", "transliteration": "nb", "object": "바구니", "phonetic": "neb", "sound_desc": "네브" },
    { "glyph": "𓏠", "transliteration": "mn", "object": "게임판", "phonetic": "men", "sound_desc": "멘" },
    { "glyph": "𓇓", "transliteration": "sw", "object": "골풀", "phonetic": "su", "sound_desc": "수" },
    { "glyph": "𓈘", "transliteration": "mr", "object": "수로 (또는 운하)", "phonetic": "mer", "sound_desc": "메르" },
    { "glyph": "𓁹", "transliteration": "ir", "object": "눈", "phonetic": "ir", "sound_desc": "이르" },
    { "glyph": "𓌳", "transliteration": "mꜣ", "object": "낫", "phonetic": "ma", "sound_desc": "마" },
    { "glyph": "𓍯", "transliteration": "wꜣ", "object": "밧줄 (또는 올가미)", "phonetic": "wa", "sound_desc": "와" },
    { "glyph": "𓉻", "transliteration": "ꜥꜣ", "object": "나무 기둥", "phonetic": "aa", "sound_desc": "아아" },
    { "glyph": "𓆼", "transliteration": "ḫꜣ", "object": "연꽃", "phonetic": "kha", "sound_desc": "카" },
    { "glyph": "𓅮", "transliteration": "pꜣ", "object": "날아가는 오리", "phonetic": "pa", "sound_desc": "파" },
    { "glyph": "𓍑", "transliteration": "ḏꜣ", "object": "불 피우는 도구", "phonetic": "dja", "sound_desc": "자 또는 쟈" },
    { "glyph": "𓍋", "transliteration": "ꜣb 또는 mr", "object": "끌 (또는 핀)", "phonetic": "ab / mer", "sound_desc": "아브 또는 메르" },
    { "glyph": "𓅬", "transliteration": "gb", "object": "거위", "phonetic": "geb", "sound_desc": "겝" },
    { "glyph": "𓆛", "transliteration": "ỉn", "object": "물고기 (틸라피아)", "phonetic": "in", "sound_desc": "인" },
    { "glyph": "𓌡", "transliteration": "wꜥ", "object": "작살", "phonetic": "wa", "sound_desc": "와" },
    { "glyph": "𓄑", "transliteration": "bḥ", "object": "치아 (상아)", "phonetic": "bah", "sound_desc": "바흐" },
    { "glyph": "𓌸", "transliteration": "mr", "object": "괭이", "phonetic": "mer", "sound_desc": "메르" },
    { "glyph": "𓄟", "transliteration": "ms", "object": "여우 가죽 셋", "phonetic": "mes", "sound_desc": "메스" },
    { "glyph": "𓁷", "transliteration": "ḥr", "object": "얼굴", "phonetic": "her", "sound_desc": "헤르" },
    { "glyph": "𓎿", "transliteration": "ḥs", "object": "물병", "phonetic": "hes", "sound_desc": "헤스" },
    { "glyph": "𓆱", "transliteration": "ḫt", "object": "나무 가지", "phonetic": "khet", "sound_desc": "헤트" },
    { "glyph": "𓅭", "transliteration": "sꜣ", "object": "오리 (아들)", "phonetic": "sa", "sound_desc": "사" },
    { "glyph": "𓍶", "transliteration": "šn", "object": "밧줄 고리", "phonetic": "shen", "sound_desc": "셴" },
    { "glyph": "𓂓", "transliteration": "kꜣ", "object": "두 팔 (카)", "phonetic": "ka", "sound_desc": "카" },
    { "glyph": "𓇾", "transliteration": "tꜣ", "object": "땅", "phonetic": "ta", "sound_desc": "타" },
    { "glyph": "𓁶", "transliteration": "tp", "object": "머리", "phonetic": "tep", "sound_desc": "텝" },
    { "glyph": "𓈋", "transliteration": "ḏw", "object": "산", "phonetic": "dju", "sound_desc": "쥬" },
    { "glyph": "𓊽", "transliteration": "ḏd", "object": "제드 기둥 (안정)", "phonetic": "djed", "sound_desc": "제드" },
    { "glyph": "𓅡", "transliteration": "bꜣ", "object": "황새 (영혼)", "phonetic": "ba", "sound_desc": "바" },
    { "glyph": "𓊨", "transliteration": "ꜣs", "object": "좌석 (왕좌)", "phonetic": "is", "sound_desc": "이스" },
    { "glyph": "𓏌", "transliteration": "mw", "object": "우유 항아리", "phonetic": "mw", "sound_desc": "무" },
    { "glyph": "𓇳", "transliteration": "rꜥ", "object": "태양", "phonetic": "ra", "sound_desc": "라" },
    { "glyph": "𓍘", "transliteration": "tỉ", "object": "공이", "phonetic": "ti", "sound_desc": "티" },
    { "glyph": "𓍃", "transliteration": "tm", "object": "썰매", "phonetic": "tem", "sound_desc": "템" },
    { "glyph": "𓏙", "transliteration": "di", "object": "원뿔 빵 (주다)", "phonetic": "di", "sound_desc": "디" },
    { "glyph": "𓂟", "transliteration": "di", "object": "빵을 든 팔 (주다)", "phonetic": "di", "sound_desc": "디" },
    { "glyph": "𓃘", "transliteration": "ib", "object": "염소 (새끼)", "phonetic": "ib", "sound_desc": "이브" },
    { "glyph": "𓏎", "transliteration": "in", "object": "다리 달린 항아리 (가져오다)", "phonetic": "in", "sound_desc": "인" },
    { "glyph": "𓍲", "transliteration": "šn", "object": "셴 고리 (영원)", "phonetic": "shen", "sound_desc": "셴" },
    { "glyph": "𓎔", "transliteration": "mḥ", "object": "채찍", "phonetic": "meh", "sound_desc": "메흐" },
    { "glyph": "𓏞", "transliteration": "sẖ", "object": "서기관의 도구 (쓰다)", "phonetic": "sesh", "sound_desc": "세쉬" },
    { "glyph": "𓍱", "transliteration": "šs", "object": "밧줄 (또는 끈)", "phonetic": "shes", "sound_desc": "쉐스" },
    { "glyph": "𓅨", "transliteration": "wr", "object": "제비", "phonetic": "wer", "sound_desc": "웨르" },
    { "glyph": "𓇨", "transliteration": "ḏr", "object": "과일 바구니", "phonetic": "djer", "sound_desc": "제르" },
    { "glyph": "𓄫", "transliteration": "ꜣw", "object": "척추 (또는 등뼈)", "phonetic": "aw", "sound_desc": "아우" },
    { "glyph": "𓊗", "transliteration": "sp", "object": "타작 마당", "phonetic": "sep", "sound_desc": "셉" },
    { "glyph": "𓄝", "transliteration": "st", "object": "화살에 찔린 가죽", "phonetic": "set", "sound_desc": "세트" },
    { "glyph": "𓈞", "transliteration": "ḥm", "object": "우물 (또는 구리/아내)", "phonetic": "hem", "sound_desc": "헴" },
    { "glyph": "𓈍", "transliteration": "ẖꜥ", "object": "언덕 너머로 떠오르는 태양 (출현)", "phonetic": "kha", "sound_desc": "카" },
    { "glyph": "𓌐", "transliteration": "tp", "object": "단검 (또는 으뜸)", "phonetic": "tep", "sound_desc": "텝" },
    { "glyph": "𓌢", "transliteration": "sn", "object": "화살촉 (또는 작살촉)", "phonetic": "sen", "sound_desc": "센" },
    { "glyph": "𓍛", "transliteration": "ḥm", "object": "빨래 방망이", "phonetic": "hem", "sound_desc": "헴" },
    { "glyph": "𓌨", "transliteration": "ẖr", "object": "도살자의 도마", "phonetic": "kher", "sound_desc": "헤르" },
    { "glyph": "𓍔", "transliteration": "tꜣ", "object": "가마 (또는 도공의 가마)", "phonetic": "ta", "sound_desc": "타" },
    { "glyph": "𓎑", "transliteration": "sꜣ", "object": "말린 매트 (보호)", "phonetic": "sa", "sound_desc": "사" },
    { "glyph": "𓆄", "transliteration": "šw", "object": "깃털", "phonetic": "shu", "sound_desc": "슈" },
    { "glyph": "𓆎", "transliteration": "km", "object": "악어 비늘 (검음)", "phonetic": "kem", "sound_desc": "켐" },
    { "glyph": "𓅝", "transliteration": "gm", "object": "따오기", "phonetic": "gem", "sound_desc": "겜" },
    { "glyph": "𓃹", "transliteration": "wn", "object": "토끼", "phonetic": "wen", "sound_desc": "웬" },
    { "glyph": "𓅑", "transliteration": "nḥ", "object": "뿔닭", "phonetic": "neh", "sound_desc": "네흐" },
    { "glyph": "𓂸", "transliteration": "mt", "object": "남근", "phonetic": "met", "sound_desc": "메트" },
    { "glyph": "𓌃", "transliteration": "md", "object": "지팡이", "phonetic": "med", "sound_desc": "메드" },
    { "glyph": "𓎘", "transliteration": "wḏ", "object": "끈", "phonetic": "wedj", "sound_desc": "웨즈" },
    { "glyph": "𓄣", "transliteration": "ib", "object": "심장", "phonetic": "ib", "sound_desc": "이브" },
    { "glyph": "𓏶", "transliteration": "im", "object": "교차된 막대", "phonetic": "im", "sound_desc": "임" },
    { "glyph": "𓐛", "transliteration": "gs", "object": "옆면 (갈비뼈)", "phonetic": "ges", "sound_desc": "게스" },
    { "glyph": "𓄻", "transliteration": "pḥ", "object": "동물의 뒷다리", "phonetic": "peh", "sound_desc": "페흐" },
    { "glyph": "𓇚", "transliteration": "ḥn", "object": "식물", "phonetic": "hen", "sound_desc": "헨" },
    { "glyph": "𓅂", "transliteration": "tw", "object": "말똥가리 (또는 새)", "phonetic": "tw", "sound_desc": "트우" }
];


