const hieroData = [
    // 1-syllable
    { "glyph": "𓄿", "transliteration": "ꜣ", "object": "이집트 독수리", "phonetic": "a", "sound_desc": "아" },
    { "glyph": "𓇋", "transliteration": "i", "object": "갈대 꽃", "phonetic": "i", "sound_desc": "이" },
    { "glyph": "𓇌", "transliteration": "y", "object": "갈대 두 개", "phonetic": "y", "sound_desc": "이이" },
    { "glyph": "𓂝", "transliteration": "ꜥ", "object": "팔 (아랫팔)", "phonetic": "a", "sound_desc": "아" },
    { "glyph": "𓅱", "transliteration": "w", "object": "메추라기 새끼", "phonetic": "u", "sound_desc": "우" },
    { "glyph": "𓃀", "transliteration": "b", "object": "발", "phonetic": "b", "sound_desc": "브" },
    { "glyph": "𓊪", "transliteration": "p", "object": "의자 (받침대)", "phonetic": "p", "sound_desc": "프" },
    { "glyph": "𓆑", "transliteration": "f", "object": "뿔달린 독사", "phonetic": "f", "sound_desc": "프" },
    { "glyph": "𓅓", "transliteration": "m", "object": "올빼미", "phonetic": "m", "sound_desc": "므" },
    { "glyph": "𓈖", "transliteration": "n", "object": "물결", "phonetic": "n", "sound_desc": "느" },
    { "glyph": "𓂋", "transliteration": "r", "object": "입", "phonetic": "r", "sound_desc": "르" },
    { "glyph": "𓉔", "transliteration": "h", "object": "갈대 오두막", "phonetic": "h", "sound_desc": "흐" },
    { "glyph": "𓎛", "transliteration": "ḥ", "object": "꼬인 심지 (아마)", "phonetic": "h", "sound_desc": "흐" },
    { "glyph": "𓐍", "transliteration": "ḫ", "object": "체 (또는 태반)", "phonetic": "kh", "sound_desc": "크" },
    { "glyph": "𓄡", "transliteration": "ẖ", "object": "짐승의 배", "phonetic": "kh", "sound_desc": "흐" },
    { "glyph": "𓊃", "transliteration": "z", "object": "문빗장", "phonetic": "z", "sound_desc": "즈" },
    { "glyph": "𓋴", "transliteration": "s", "object": "접은 천", "phonetic": "s", "sound_desc": "쓰" },
    { "glyph": "𓈙", "transliteration": "š", "object": "연못", "phonetic": "sh", "sound_desc": "쉬" },
    { "glyph": "𓈎", "transliteration": "q", "object": "언덕", "phonetic": "q", "sound_desc": "꾸" },
    { "glyph": "𓎡", "transliteration": "k", "object": "바구니", "phonetic": "k", "sound_desc": "크" },
    { "glyph": "𓎼", "transliteration": "g", "object": "항아리 받침대", "phonetic": "g", "sound_desc": "그" },
    { "glyph": "𓏏", "transliteration": "t", "object": "빵 (또는 떡)", "phonetic": "t", "sound_desc": "트" },
    { "glyph": "𓍿", "transliteration": "ṯ", "object": "매는 끈 (밧줄)", "phonetic": "tj", "sound_desc": "츠" },
    { "glyph": "𓂧", "transliteration": "d", "object": "손", "phonetic": "d", "sound_desc": "드" },
    { "glyph": "𓆓", "transliteration": "ḏ", "object": "코브라", "phonetic": "dj", "sound_desc": "즈" },
    { "glyph": "𓃭", "transliteration": "l", "object": "사자", "phonetic": "l", "sound_desc": "르" },
    { "glyph": "𓏲", "transliteration": "w", "object": "소용돌이 (밧줄)", "phonetic": "w", "sound_desc": "우" },
    { "glyph": "𓏭", "transliteration": "y", "object": "빗금 두 개", "phonetic": "y", "sound_desc": "이" },

    // 2-syllable
    { "glyph": "𓉐", "transliteration": "pr", "object": "집", "phonetic": "per", "sound_desc": "페르" },
    { "glyph": "𓎟", "transliteration": "nb", "object": "바구니", "phonetic": "neb", "sound_desc": "네브" },
    { "glyph": "𓏠", "transliteration": "mn", "object": "게임판", "phonetic": "men", "sound_desc": "멘" },
    { "glyph": "𓇓", "transliteration": "sw", "object": "골풀", "phonetic": "su", "sound_desc": "수" },
    { "glyph": "𓈘", "transliteration": "mr", "object": "수로 (또는 운하)", "phonetic": "mer", "sound_desc": "메르" },
    { "glyph": "𓁹", "transliteration": "ir", "object": "눈", "phonetic": "ir", "sound_desc": "이르" },
    { "glyph": "𓌳", "transliteration": "mꜣ", "object": "낫", "phonetic": "ma", "sound_desc": "마" },
    { "glyph": "𓍯", "transliteration": "wꜣ", "object": "밧줄 (또는 올가미)", "phonetic": "wa", "sound_desc": "와" },
    { "glyph": "𓉻", "transliteration": "ꜥꜣ", "object": "나무 기둥", "phonetic": "aa", "sound_desc": "아아" },
    { "glyph": "𓆼", "transliteration": "ḫꜣ", "object": "연꽃", "phonetic": "kha", "sound_desc": "카" },
    { "glyph": "𓅮", "transliteration": "pꜣ", "object": "날아가는 오리", "phonetic": "pa", "sound_desc": "파" },
    { "glyph": "𓍑", "transliteration": "ḏꜣ", "object": "불 피우는 도구", "phonetic": "dja", "sound_desc": "자 또는 쟈" },
    { "glyph": "𓍋", "transliteration": "ꜣb 또는 mr", "object": "끌 (또는 핀)", "phonetic": "ab / mer", "sound_desc": "아브 또는 메르" },
    { "glyph": "𓅬", "transliteration": "gb", "object": "거위", "phonetic": "geb", "sound_desc": "겝" },
    { "glyph": "𓆛", "transliteration": "ỉn", "object": "물고기 (틸라피아)", "phonetic": "in", "sound_desc": "인" },
    { "glyph": "𓌡", "transliteration": "wꜥ", "object": "작살", "phonetic": "wa", "sound_desc": "와" },
    { "glyph": "𓄑", "transliteration": "bḥ", "object": "치아 (상아)", "phonetic": "bah", "sound_desc": "바흐" },
    { "glyph": "𓌸", "transliteration": "mr", "object": "괭이", "phonetic": "mer", "sound_desc": "메르" },
    { "glyph": "𓄟", "transliteration": "ms", "object": "여우 가죽 셋", "phonetic": "mes", "sound_desc": "메스" },
    { "glyph": "𓁷", "transliteration": "ḥr", "object": "얼굴", "phonetic": "her", "sound_desc": "헤르" },
    { "glyph": "𓎿", "transliteration": "ḥs", "object": "물병", "phonetic": "hes", "sound_desc": "헤스" },
    { "glyph": "𓆱", "transliteration": "ḫt", "object": "나무 가지", "phonetic": "khet", "sound_desc": "헤트" },
    { "glyph": "𓅭", "transliteration": "sꜣ", "object": "오리 (아들)", "phonetic": "sa", "sound_desc": "사" },
    { "glyph": "𓍶", "transliteration": "šn", "object": "밧줄 고리", "phonetic": "shen", "sound_desc": "셴" },
    { "glyph": "𓂓", "transliteration": "kꜣ", "object": "두 팔 (카)", "phonetic": "ka", "sound_desc": "카" },
    { "glyph": "𓇾", "transliteration": "tꜣ", "object": "땅", "phonetic": "ta", "sound_desc": "타" },
    { "glyph": "𓁶", "transliteration": "tp", "object": "머리", "phonetic": "tep", "sound_desc": "텝" },
    { "glyph": "𓈋", "transliteration": "ḏw", "object": "산", "phonetic": "dju", "sound_desc": "쥬" },
    { "glyph": "𓊽", "transliteration": "ḏd", "object": "제드 기둥 (안정)", "phonetic": "djed", "sound_desc": "제드" },
    { "glyph": "𓅡", "transliteration": "bꜣ", "object": "황새 (영혼)", "phonetic": "ba", "sound_desc": "바" },
    { "glyph": "𓊨", "transliteration": "ꜣs", "object": "좌석 (왕좌)", "phonetic": "is", "sound_desc": "이스" },
    { "glyph": "𓏌", "transliteration": "mw", "object": "우유 항아리", "phonetic": "mw", "sound_desc": "무" },
    { "glyph": "𓇳", "transliteration": "rꜥ", "object": "태양", "phonetic": "ra", "sound_desc": "라" },
    { "glyph": "𓍘", "transliteration": "tỉ", "object": "공이", "phonetic": "ti", "sound_desc": "티" },
    { "glyph": "𓍃", "transliteration": "tm", "object": "썰매", "phonetic": "tem", "sound_desc": "템" },
    { "glyph": "𓏙", "transliteration": "di", "object": "원뿔 빵 (주다)", "phonetic": "di", "sound_desc": "디" },
    { "glyph": "𓂟", "transliteration": "di", "object": "빵을 든 팔 (주다)", "phonetic": "di", "sound_desc": "디" },
    { "glyph": "𓃘", "transliteration": "ib", "object": "염소 (새끼)", "phonetic": "ib", "sound_desc": "이브" },
    { "glyph": "𓏎", "transliteration": "in", "object": "다리 달린 항아리 (가져오다)", "phonetic": "in", "sound_desc": "인" },
    { "glyph": "𓍲", "transliteration": "šn", "object": "셴 고리 (영원)", "phonetic": "shen", "sound_desc": "셴" },
    { "glyph": "𓎔", "transliteration": "mḥ", "object": "채찍", "phonetic": "meh", "sound_desc": "메흐" },
    { "glyph": "𓏞", "transliteration": "sẖ", "object": "서기관의 도구 (쓰다)", "phonetic": "sesh", "sound_desc": "세쉬" },
    { "glyph": "𓍱", "transliteration": "šs", "object": "밧줄 (또는 끈)", "phonetic": "shes", "sound_desc": "쉐스" },
    { "glyph": "𓅨", "transliteration": "wr", "object": "제비", "phonetic": "wer", "sound_desc": "웨르" },
    { "glyph": "𓇨", "transliteration": "ḏr", "object": "과일 바구니", "phonetic": "djer", "sound_desc": "제르" },
    { "glyph": "𓄫", "transliteration": "ꜣw", "object": "척추 (또는 등뼈)", "phonetic": "aw", "sound_desc": "아우" },
    { "glyph": "𓊗", "transliteration": "sp", "object": "타작 마당", "phonetic": "sep", "sound_desc": "셉" },
    { "glyph": "𓄝", "transliteration": "st", "object": "화살에 찔린 가죽", "phonetic": "set", "sound_desc": "세트" },
    { "glyph": "𓈞", "transliteration": "ḥm", "object": "우물 (또는 구리/아내)", "phonetic": "hem", "sound_desc": "헴" },
    { "glyph": "𓈍", "transliteration": "ẖꜥ", "object": "언덕 너머로 떠오르는 태양 (출현)", "phonetic": "kha", "sound_desc": "카" },
    { "glyph": "𓌐", "transliteration": "tp", "object": "단검 (또는 으뜸)", "phonetic": "tep", "sound_desc": "텝" },
    { "glyph": "𓌢", "transliteration": "sn", "object": "화살촉 (또는 작살촉)", "phonetic": "sen", "sound_desc": "센" },
    { "glyph": "𓍛", "transliteration": "ḥm", "object": "빨래 방망이", "phonetic": "hem", "sound_desc": "헴" },
    { "glyph": "𓌨", "transliteration": "ẖr", "object": "도살자의 도마", "phonetic": "kher", "sound_desc": "헤르" },
    { "glyph": "𓍔", "transliteration": "tꜣ", "object": "가마 (또는 도공의 가마)", "phonetic": "ta", "sound_desc": "타" },
    { "glyph": "𓎑", "transliteration": "sꜣ", "object": "말린 매트 (보호)", "phonetic": "sa", "sound_desc": "사" },
    { "glyph": "𓆄", "transliteration": "šw", "object": "깃털", "phonetic": "shu", "sound_desc": "슈" },
    { "glyph": "𓆎", "transliteration": "km", "object": "악어 비늘 (검음)", "phonetic": "kem", "sound_desc": "켐" },
    { "glyph": "𓅝", "transliteration": "gm", "object": "따오기", "phonetic": "gem", "sound_desc": "겜" },
    { "glyph": "𓃹", "transliteration": "wn", "object": "토끼", "phonetic": "wen", "sound_desc": "웬" },
    { "glyph": "𓅑", "transliteration": "nḥ", "object": "뿔닭", "phonetic": "neh", "sound_desc": "네흐" },
    { "glyph": "𓂸", "transliteration": "mt", "object": "남근", "phonetic": "met", "sound_desc": "메트" },
    { "glyph": "𓌃", "transliteration": "md", "object": "지팡이", "phonetic": "med", "sound_desc": "메드" },
    { "glyph": "𓎘", "transliteration": "wḏ", "object": "끈", "phonetic": "wedj", "sound_desc": "웨즈" },
    { "glyph": "𓄣", "transliteration": "ib", "object": "심장", "phonetic": "ib", "sound_desc": "이브" },
    { "glyph": "𓏶", "transliteration": "im", "object": "교차된 막대", "phonetic": "im", "sound_desc": "임" },
    { "glyph": "𓐛", "transliteration": "gs", "object": "옆면 (갈비뼈)", "phonetic": "ges", "sound_desc": "게스" },
    { "glyph": "𓄻", "transliteration": "pḥ", "object": "동물의 뒷다리", "phonetic": "peh", "sound_desc": "페흐" },
    { "glyph": "𓇚", "transliteration": "ḥn", "object": "식물", "phonetic": "hen", "sound_desc": "헨" },
    { "glyph": "𓅂", "transliteration": "tw", "object": "말똥가리 (또는 새)", "phonetic": "tw", "sound_desc": "트우" },

    // 3-syllable
    { "glyph": "𓋹", "transliteration": "ꜥnḫ", "object": "샌들 끈 (생명)", "phonetic": "ankh", "sound_desc": "앙크" },
    { "glyph": "𓄤", "transliteration": "nfr", "object": "심장과 기관 (좋음/아름다움)", "phonetic": "nefer", "sound_desc": "네페르" },
    { "glyph": "𓊵", "transliteration": "ḥtp", "object": "제물 돗자리 (평화/만족)", "phonetic": "hotep", "sound_desc": "호텝" },
    { "glyph": "𓆣", "transliteration": "ḫpr", "object": "쇠똥구리 (되다/변화)", "phonetic": "kheper", "sound_desc": "케페르" },
    { "glyph": "𓌂", "transliteration": "sḫm", "object": "홀 (힘/권능)", "phonetic": "sekhem", "sound_desc": "세켐" },
    { "glyph": "𓄔", "transliteration": "sḏm", "object": "귀 (듣다)", "phonetic": "sedjem", "sound_desc": "세젬" },
    { "glyph": "𓎝", "transliteration": "wꜣḥ", "object": "심지 (지속되다)", "phonetic": "wah", "sound_desc": "와흐" },
    { "glyph": "𓌀", "transliteration": "wꜣs", "object": "와스 홀 (권력/지배)", "phonetic": "was", "sound_desc": "와스" },
    { "glyph": "𓊹", "transliteration": "nṯr", "object": "깃발 (신)", "phonetic": "netjer", "sound_desc": "네체르" },
    { "glyph": "𓐙", "transliteration": "mꜣꜥ", "object": "받침대 (진실/정의)", "phonetic": "maa", "sound_desc": "마아" },
    { "glyph": "𓅟", "transliteration": "dšr", "object": "홍학 (붉다)", "phonetic": "desher", "sound_desc": "데쉐르" },
    { "glyph": "𓉺", "transliteration": "iwn", "object": "기둥 (이운)", "phonetic": "iwn", "sound_desc": "이운" },
    { "glyph": "𓆈", "transliteration": "ꜥšꜣ", "object": "도마뱀 (많다)", "phonetic": "asha", "sound_desc": "아샤" },

    // 4-syllable
    { "glyph": "𓄪", "transliteration": "jmꜣḫ", "object": "척추와 갈비뼈 (존경/명예)", "phonetic": "imakh", "sound_desc": "이마크" },
    { "glyph": "𓋣", "transliteration": "ḫprš", "object": "청색 왕관 (케프레시)", "phonetic": "khepresh", "sound_desc": "케프레시" },
    { "glyph": "𓆰", "transliteration": "rnpt", "object": "종려나무 가지 (해/년)", "phonetic": "renpet", "sound_desc": "렌펫" },
    { "glyph": "𓁢", "transliteration": "inpw", "object": "자칼 신 (아누비스)", "phonetic": "anubis", "sound_desc": "인푸" },
    { "glyph": "𓋔", "transliteration": "bity", "object": "꿀벌 (하 이집트의 왕)", "phonetic": "bity", "sound_desc": "비티" },
    { "glyph": "𓊖", "transliteration": "niwt", "object": "교차로가 있는 마을 (도시/마을)", "phonetic": "niwt", "sound_desc": "니우트" },
    { "glyph": "𓆉", "transliteration": "štw", "object": "거북 (악/어둠/죽음)", "phonetic": "shetu", "sound_desc": "셰투" },

    // 5-syllable
    { "glyph": "𓋀", "transliteration": "jmntt", "object": "서쪽의 상징 (이멘테트/서쪽)", "phonetic": "imentet", "sound_desc": "이멘테트" },
    { "glyph": "𓋁", "transliteration": "jꜣbtt", "object": "동쪽의 상징 (이아브테트/동쪽)", "phonetic": "iabtet", "sound_desc": "이아브테트" },
    { "glyph": "𓉡", "transliteration": "ḥwt-ḥr", "object": "호루스의 집 (하토르)", "phonetic": "hathor", "sound_desc": "하토르" },
    { "glyph": "𓇅", "transliteration": "wꜣḏyt", "object": "파피루스 줄기 (와제트)", "phonetic": "wadjet", "sound_desc": "와제트" },
    { "glyph": "𓅝", "transliteration": "ḏḥwty", "object": "따오기 (토트/제후티)", "phonetic": "thoth", "sound_desc": "제후티" }
];
